SELECT SUM(b.SCORE) AS SCORE, b.EMP_NO, a.EMP_NAME, a.POSITION, a.EMAIL
FROM HR_EMPLOYEES AS a
INNER JOIN HR_GRADE AS b ON a.EMP_NO = b.EMP_NO
GROUP BY b.YEAR, b.EMP_NO
HAVING b.YEAR = "2022"
ORDER BY 1 DESC
LIMIT 1;
