-- ROUND 함수의 숫자: 해당 실수를 반올림해서 (숫자)자리 실수로 만든다.
SELECT ROUTE, 
  CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), "km") AS TOTAL_DISTANCE, 
  CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), "km") AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY 1 DESC;
