-- 성과 이름은 UNIQUE하지 않아서 여러 개가 있을 수도 있기 때문에 DISTINCT를 사용.
SELECT DISTINCT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS AS A
INNER JOIN SKILLCODES AS B ON (A.SKILL_CODE & B.CODE) = B.CODE
WHERE B.NAME IN ("Python", "C#")
ORDER BY A.ID;
