WITH MAX_YEAR_DEV_TABLE AS (
  SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
  FROM ECOLI_DATA
  GROUP BY 1
), 
YEAR_PER_ECOLI_DATA AS (
  SELECT A.ID AS ID,
    YEAR(A.DIFFERENTIATION_DATE) AS YEAR, 
    (MAX_SIZE_OF_COLONY - A.SIZE_OF_COLONY) AS YEAR_DEV
  FROM ECOLI_DATA AS A
  INNER JOIN MAX_YEAR_DEV_TABLE AS B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
)

SELECT YEAR, YEAR_DEV, ID
FROM YEAR_PER_ECOLI_DATA
ORDER BY YEAR, YEAR_DEV;
